import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavbarOf from '@/components/Navbar'
import Profile from '@/components/Profile'
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'
import ContactMe from '@/components/ContactMe'

const inter = Inter({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavbarOf/>
      <Profile/>
      <Skills/>
      <Projects/>
      <ContactMe/>
      {children}
      </body>
    </html>
  )
}
